//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolnicaSims.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolnicaSims.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital survey.
        /// </summary>
        internal static string AnketaBolnica {
            get {
                return ResourceManager.GetString("AnketaBolnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor survey.
        /// </summary>
        internal static string AnketaDoktor {
            get {
                return ResourceManager.GetString("AnketaDoktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy hospital.
        /// </summary>
        internal static string BolnicaZdravo {
            get {
                return ResourceManager.GetString("BolnicaZdravo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doktor {
            get {
                return ResourceManager.GetString("Doktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string IdTermina {
            get {
                return ResourceManager.GetString("IdTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string ImePrezimePacijenta {
            get {
                return ResourceManager.GetString("ImePrezimePacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a theme.
        /// </summary>
        internal static string IzaberiteTemu {
            get {
                return ResourceManager.GetString("IzaberiteTemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change appointment.
        /// </summary>
        internal static string Izmeni {
            get {
                return ResourceManager.GetString("Izmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of days.
        /// </summary>
        internal static string KolikoDana {
            get {
                return ResourceManager.GetString("KolikoDana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends at.
        /// </summary>
        internal static string KrajTermina {
            get {
                return ResourceManager.GetString("KrajTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Kreni {
            get {
                return ResourceManager.GetString("Kreni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        internal static string Lek {
            get {
                return ResourceManager.GetString("Lek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light mode.
        /// </summary>
        internal static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel appointment.
        /// </summary>
        internal static string Otkazi {
            get {
                return ResourceManager.GetString("Otkazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Prostorija {
            get {
                return ResourceManager.GetString("Prostorija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times per day.
        /// </summary>
        internal static string PutaDnevno {
            get {
                return ResourceManager.GetString("PutaDnevno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string ReceptiTab {
            get {
                return ResourceManager.GetString("ReceptiTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of recipes.
        /// </summary>
        internal static string TabelaRecepata {
            get {
                return ResourceManager.GetString("TabelaRecepata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string TerminiTab {
            get {
                return ResourceManager.GetString("TerminiTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string VremeTermina {
            get {
                return ResourceManager.GetString("VremeTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make appointment.
        /// </summary>
        internal static string Zakazi {
            get {
                return ResourceManager.GetString("Zakazi", resourceCulture);
            }
        }
    }
}
